version: '3.9'

services:
  bookary:
    container_name: bookary-app
    image: bookary:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=localhost
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - db

  db:
    container_name: bookary-db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
